### ISSUE TITLE
Wrong link for "Introduction to Galaxy" slides

### ISSUE THREAD

**Issue by nsoranzo** [shiltemann/gcc2021-training#14]
I may have found a bug in the https://galaxyproject.org/events/gcc2021/training/ website: in the "Introduction to Galaxy" (which is in all tracks), the link for "Slides: A Slightly Longer Introduction to Galaxy" points to the general list of videos instead of a slide deck.

**Comment by shiltemann** [comment]
Thanks for catching that! should be fixed now
